apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -stage

bases:
- ../../base

commonLabels:
  app: rest-example-stage

patches:
- ./deploy-replicas-patch.yaml

configMapGenerator:
- name: rest-example-configuration
  envs:
  - properties.env

images:
- name: rest-example
  newName: image-registry.openshift-image-registry.svc:5000/zz-dev/rest-example
  newTag: latest