apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: catalog-build
  generateName: demo-ci-run
spec:
  pipelineRef:
    name: ci-demo
  serviceAccountName: pipeline
  workspaces:
  - name: app-source
    persistentVolumeClaim:
      claimName: source-pvc
  - name: maven-settings
    emptyDir: {}