apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zz
spec:
  project: default
  source:
    repoURL: https://github.com/clbartolome/cloud-native-dev-demo
    targetRevision: master
    path: application-cicd/deploy/overlays/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: zz-stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true